PARAMETER_VALUES = [
    'tavg',
    'pre',
    'pet',
    'n_Qdaily',
    'median_Qdaily',
    'n_Q_annual',
    'median_Q_annual',
    'n_Q_wrtds',
    'median_Q_wrtds',
    'n_NO3',
    'median_NO3N',
    'n_Nmin',
    'median_Nmin',
    'n_TN',
    'median_TN',
    'n_PO4',
    'median_PO4P',
    'n_TP',
    'median_TP',
    'n_DOC',
    'median_DOC',
    'n_TOC',
    'median_TOC',
    'n_C_NO3',
    'median_C_NO3',
    'n_C_PO4',
    'median_C_PO4',
    'n_C_Nmin',
    'median_C_Nmin',
    'n_C_TN',
    'median_C_TN',
    'n_C_TP',
    'median_C_TP',
    'n_C_DOC',
    'median_C_DOC',
    'n_C_TOC',
    'median_C_TOC',
    'n_FNC_NO3',
    'median_FNC_NO3',
    'n_FNC_PO4',
    'median_FNC_PO4',
    'n_FNC_Nmin',
    'median_FNC_Nmin',
    'n_FNC_TN',
    'median_FNC_TN',
    'n_FNC_TP',
    'median_FNC_TP',
    'n_FNC_DOC',
    'median_FNC_DOC',
    'n_FNC_TOC',
    'median_FNC_TOC',
    'mean_Flux_NO3',
    'mean_FNFlux_NO3',
    'mean_Flux_PO4',
    'mean_FNFlux_PO4',
    'mean_Flux_Nmin',
    'mean_FNFlux_Nmin',
    'mean_Flux_TN',
    'mean_FNFlux_TN',
    'mean_Flux_TP',
    'mean_FNFlux_TP',
    'mean_Flux_DOC',
    'mean_FNFlux_DOC',
    'mean_Flux_TOC',
    'mean_FNFlux_TOC',
    'N_nonagri',
    'N_agri',
    'N_total',
    'N_agri_frac',
]

PARAMETER_SELECTION = []

DATA_ALIASES = {
    'tavg':             'temperature',
    'pre':              'precipitation',
    'pet':              'potential evaporation',
    'n_Qdaily':         'surface water quantity',
    'median_Qdaily':    'surface water quantity',
    'n_Q_annual':       'surface water quantity',
    'median_Q_annual':  'surface water quantity',
    'n_Q_wrtds':        'surface water quantity',
    'median_Q_wrtds':   'surface water quantity',
    'n_NO3':            'surface water quality',
    'median_NO3N':      'surface water quality',
    'n_Nmin':           'surface water quality',
    'median_Nmin':      'surface water quality',
    'n_TN':             'surface water quality',
    'median_TN':        'surface water quality',
    'n_C_NO3':          'surface water quality',
    'median_C_NO3':     'surface water quality',
    'n_C_Nmin':         'surface water quality',
    'median_C_Nmin':    'surface water quality',
    'n_C_TN':           'surface water quality',
    'median_C_TN':      'surface water quality',
    'n_FNC_NO3':        'surface water quality',
    'median_FNC_NO3':   'surface water quality',
    'n_FNC_Nmin':       'surface water quality',
    'median_FNC_Nmin':  'surface water quality',
    'n_FNC_TN':         'surface water quality',
    'median_FNC_TN':    'surface water quality',
    'mean_Flux_NO3':    'surface water quality',
    'mean_FNFlux_NO3':  'surface water quality',
    'mean_Flux_Nmin':   'surface water quality',
    'mean_FNFlux_Nmin': 'surface water quality',
    'mean_Flux_TN':     'surface water quality',
    'mean_FNFlux_TN':   'surface water quality',
    'n_PO4':            'surface water quality',
    'median_PO4P':      'surface water quality',
    'n_TP':             'surface water quality',
    'median_TP':        'surface water quality',
    'n_C_PO4':          'surface water quality',
    'median_C_PO4':     'surface water quality',
    'n_C_TP':           'surface water quality',
    'median_C_TP':      'surface water quality',
    'n_FNC_PO4':        'surface water quality',
    'median_FNC_PO4':   'surface water quality',
    'n_FNC_TP':         'surface water quality',
    'median_FNC_TP':    'surface water quality',
    'mean_Flux_PO4':    'surface water quality',
    'mean_FNFlux_PO4':  'surface water quality',
    'mean_Flux_TP':     'surface water quality',
    'mean_FNFlux_TP':   'surface water quality',
    'n_DOC':            'surface water quality',
    'median_DOC':       'surface water quality',
    'n_TOC':            'surface water quality',
    'median_TOC':       'surface water quality',
    'n_C_DOC':          'surface water quality',
    'median_C_DOC':     'surface water quality',
    'n_C_TOC':          'surface water quality',
    'median_C_TOC':     'surface water quality',
    'n_FNC_DOC':        'surface water quality',
    'median_FNC_DOC':   'surface water quality',
    'n_FNC_TOC':        'surface water quality',
    'median_FNC_TOC':   'surface water quality',
    'mean_Flux_DOC':    'surface water quality',
    'mean_FNFlux_DOC':  'surface water quality',
    'mean_Flux_TOC':    'surface water quality',
    'mean_FNFlux_TOC':  'surface water quality',
    'N_nonagri':        'surface water quality',
    'N_agri':           'surface water quality',
    'N_total':          'surface water quality',
    'N_agri_frac':      'surface water quality',
}

GLOBAL_MAPPING = {
    'tavg':             "Temperature [°C]",
    'pre':              "Precipitation total [mm]",
    'pet':              "Potential Evaporation [m]",
    'n_Qdaily':         "No. of Daily Discharge Observations [-]",
    'median_Qdaily':    "Mean Daily Discharge [m³/s]",
    'n_Q_annual':       "No. of Discharge Observations on Sampling Days Annual [-]",
    'median_Q_annual':  "Median Discharge on Sampling Days Annual [m³/s]",
    'n_Q_wrtds':        "WRTDS No. of Discharge Observations [-]",
    'median_Q_wrtds':   "WRTDS Median Monthly Discharge [m³/s]",
    'median_NO3N':      "Nitrate Concentration NO3-N [mg N/L]",
    'n_NO3':            "No. of Nitrate Observations [-]",
    'median_Nmin':      "Mineral Nitrogen Concentration Nmin [mg N/L]",
    'n_Nmin':           "No. of Mineral Nitrogen Observations [-]",
    'median_TN':        "Total Nitrogen Concentration TN [mg N/L]",
    'n_TN':             "No. of Total Nitrogen Observations [-]",
    'median_C_NO3':     "WRTDS Median Nitrate Concentration NO3-N [mg N/L]",
    'n_C_NO3':          "WRTDS No. of Nitrate Observations [-]",
    'median_C_Nmin':    "WRTDS Median Mineral Nitrogen Concentration Nmin [mg N/L]",
    'n_C_Nmin':         "WRTDS No. of Mineral Nitrogen Observations [-]",
    'median_C_TN':      "WRTDS Median Total Nitrogen Concentration TN [mg N/L]",
    'n_C_TN':           "WRTDS No. of Total Nitrogen Observations [-]",
    'median_FNC_NO3':   "WRTDS Flow-Normalized Nitrate Concentration NO3-N [mg N/L]",
    'n_FNC_NO3':        "WRTDS No. of Flow-Normalized Nitrate Values [-]",
    'median_FNC_Nmin':  "WRTDS Flow-Normalized Mineral Nitrogen Concentration Nmin [mg N/L]",
    'n_FNC_Nmin':       "WRTDS No. of Flow-Normalized Mineral Nitrogen Values [-]",
    'median_FNC_TN':    "WRTDS Flow-Normalized Total Nitrogen Concentration TN [mg N/L]",
    'n_FNC_TN':         "WRTDS No. of Flow-Normalized Total Nitrogen Values [-]",
    'mean_Flux_NO3':    "WRTDS Mean Nitrate Flux NO3-N [kg N/ha/month]",
    'mean_FNFlux_NO3':  "WRTDS Mean Flow-Normalized Nitrate Flux NO3-N [kg N/ha/month]",
    'mean_Flux_Nmin':   "WRTDS Mean Mineral Nitrogen Flux Nmin [kg N/ha/month]",
    'mean_FNFlux_Nmin': "WRTDS Mean Flow-Normalized Mineral Nitrogen Flux Nmin [kg N/ha/month]",
    'mean_Flux_TN':     "WRTDS Mean Total Nitrogen Flux TN [kg N/ha/month]",
    'mean_FNFlux_TN':   "WRTDS Mean Flow-Normalized Total Nitrogen Flux TN [kg N/ha/month]",
    'median_PO4P':      "Phosphate Concentration PO4-P [mg P/L]",
    'n_PO4':            "No. of Phosphate Observations [-]",
    'median_TP':        "Total Phosphorus Concentration TP [mg P/L]",
    'n_TP':             "No. of Total Phosphorus Observations [-]",
    'median_C_PO4':     "WRTDS Median Phosphate Concentration PO4-P [mg P/L]",
    'n_C_PO4':          "WRTDS No. of Phosphate Observations [-]",
    'median_C_TP':      "WRTDS Median Total Phosphorus Concentration TP [mg P/L]",
    'n_C_TP':           "WRTDS No. of Total Phosphorus Observations [-]",
    'median_FNC_PO4':   "WRTDS Flow-Normalized Phosphate Concentration PO4-P [mg P/L]",
    'n_FNC_PO4':        "WRTDS No. of Flow-Normalized Phosphate Values [-]",
    'median_FNC_TP':    "WRTDS Flow-Normalized Total Phosphorus Concentration TP [mg P/L]",
    'n_FNC_TP':         "WRTDS No. of Flow-Normalized Total Phosphorus Values [-]",
    'mean_Flux_PO4':    "WRTDS Mean Phosphate Flux PO4-P [kg P/ha/month]",
    'mean_FNFlux_PO4':  "WRTDS Mean Flow-Normalized Phosphate Flux PO4-P [kg P/ha/month]",
    'mean_Flux_TP':     "WRTDS Mean Total Phosphorus Flux TP [kg P/ha/month]",
    'mean_FNFlux_TP':   "WRTDS Mean Flow-Normalized Total Phosphorus Flux TP [kg P/ha/month]",
    'median_DOC':       "Dissolved Organic Carbon Concentration DOC [mg C/L]",
    'n_DOC':            "No. of DOC Observations [-]",
    'median_TOC':       "Total Organic Carbon Concentration TOC [mg C/L]",
    'n_TOC':            "No. of TOC Observations [-]",
    'median_C_DOC':     "WRTDS Median DOC Concentration [mg C/L]",
    'n_C_DOC':          "WRTDS No. of DOC Observations [-]",
    'median_C_TOC':     "WRTDS Median TOC Concentration [mg C/L]",
    'n_C_TOC':          "WRTDS No. of TOC Observations [-]",
    'median_FNC_DOC':   "WRTDS Flow-Normalized DOC Concentration [mg C/L]",
    'n_FNC_DOC':        "WRTDS No. of Flow-Normalized DOC Values [-]",
    'median_FNC_TOC':   "WRTDS Flow-Normalized TOC Concentration [mg C/L]",
    'n_FNC_TOC':        "WRTDS No. of Flow-Normalized TOC Values [-]",
    'mean_Flux_DOC':    "WRTDS Mean DOC Flux [kg C/ha/month]",
    'mean_FNFlux_DOC':  "WRTDS Mean Flow-Normalized DOC Flux [kg C/ha/month]",
    'mean_Flux_TOC':    "WRTDS Mean TOC Flux [kg C/ha/month]",
    'mean_FNFlux_TOC':  "WRTDS Mean Flow-Normalized TOC Flux [kg C/ha/month]",
    'N_nonagri':        "Non-Agricultural Nitrogen Surplus [kg N/ha/yr]",
    'N_agri':           "Agricultural Nitrogen Surplus [kg N/ha/yr]",
    'N_total':          "Total Nitrogen Surplus [kg N/ha/yr]",
    'N_agri_frac':      "Agricultural Fraction of Nitrogen Surplus [-]",
}